apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-netflix
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#   - port: {{ .Values.service.port }}
#     targetPort: 80
#   selector:
#     app: netflix
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}       # 80
      targetPort: {{ .Values.service.targetPort | default 3000 }}  # make flexible
      protocol: TCP
      name: http
  selector:
    app: netflix