apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-youtube
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
      - name: youtube
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
